apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sync-waves
    server: https://kubernetes.default.svc
  project: default
  source:
    path: staging/sync-waves
    repoURL: https://github.com/hqzhang/argocd-example-apps
    targetRevision: HEAD
